

name: GitHub actions demo
run-name: Testing our Github actions 

on: [push]

jobs:
  basic_workflow:
    runs-in: ubuntu-latest
    stepa:
      - run: echo "Job basic workflow is executing as part of new workflow"
